services:
  data-collector:
    cap_add:
      - NET_RAW
    build:
      context: ./data-collector
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - data-collector:/storage
      - ./config.yml:/config.yml:ro
    networks:
      - server-monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - db-data:/prometheus
    networks:
      - server-monitoring
    depends_on:
      - data-collector
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${GRAFANA_ANONYMOUS_ENABLED:-false}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=${GRAFANA_DISABLE_ADMIN:-true}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-P9BfXCZ{d}{7pdbMv+nhQB<QIT#0Ws+}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
    ports:
      - "${GRAFANA_BIND_ADDRESS:-127.0.0.1}:${GRAFANA_PORT:-8080}:3000"
    networks:
      - server-monitoring
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  db-data:
  grafana-data:
  data-collector:

networks:
  server-monitoring:
    driver: bridge
